version: '3.8'

services:
  db:
    image: postgres:15
    container_name: clinic-db
    environment:
      POSTGRES_DB: clinic
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"